# Commented lines that are ignored starte with the '#' mark.
# # A helpful tutorial for more information on make
# # https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all : main.c my_bst.c
	clang -g -o main main.c my_bst.c
clean :
	rm main
